LoaderAppApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using LoaderAppApi.Areas.HelpPage.ModelDescriptions;

namespace LoaderAppApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

LoaderAppApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using LoaderAppApi.Areas.HelpPage.ModelDescriptions;
using LoaderAppApi.Areas.HelpPage.Models;

namespace LoaderAppApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

LoaderAppApi/Controllers/AdminController/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoadProject.Controllers.AdminController
{
    public class AdminController : Controller
    {
        // GET: AdminMain
        public ActionResult AdminMain()
        {
            return View();
        }


        public ActionResult viewAvailableOrders()
        {

            return View();
        }

        public ActionResult viewAvailableQuotes()
        {

            return View();
        }

        public ActionResult viewQuoteDetails()
        {

            return View();
        }
        public ActionResult AcceptQuote()
        {

            return View();
        }

        public ActionResult updateOrderAsConfirmedToTransportOwner()
        {

            return View();
        }

        public ActionResult changeStatusToTransit()
        {

            return View();
        }

        public ActionResult changeStatusToCompleted()
        {

            return View();
        }



    }
}

LoaderAppApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoaderAppApi.Controllers
{
    public class HomeController : Controller
    {
        // Comment2
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

LoaderAppApi/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace LoaderAppApi.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

LoaderAppApi/Views/Admin/AcceptQuote.cshtml
@{
    ViewBag.Title = "AcceptQuote";
}

<h2>AcceptQuote</h2>

LoaderAppApi/Views/Admin/AdminMain.cshtml
@{
    ViewBag.Title = "Admin";
}

<body>

    <div class="row" style="text-align:center;">
        <h1>Welcome to Admin panel</h1>
    </div>

    <div class="row" style="margin-top:100px; align-content:center;">

        <div class="col-lg-4"></div>
        <div class="col-lg-4">

            <div class="row">
                <button type="button" onclick="location.href='@Url.Action("viewAvailableOrders", "Admin")'">View Available Orders</button>

            </div>
            <div class="row" style="margin-top:30px;">
                <button type="button" onclick="location.href='@Url.Action("viewAvailableQuotes", "Admin")'">View Available Quotes</button>

            </div>

            <div class="row" style="margin-top:30px;">
                <button type="button" onclick="location.href='@Url.Action("updateOrderAsConfirmedToTransportOwner", "Admin")'">update order as Confirmed to Transport Owner</button>

            </div>

            <div class="row" style="margin-top:30px;">
                <button type="button" onclick="location.href='@Url.Action("changeStatusToTransit", "Admin")'">Change Status of order to Transit</button>

            </div>
            <div class="row" style="margin-top:30px;">
                <button type="button" onclick="location.href='@Url.Action("changeStatusToCompleted", "Admin")'">Change Status of order to Completed</button>

            </div>


        </div>
        <div class="col-lg-4"></div>
    </div>


</body>

LoaderAppApi/Views/Admin/changeStatusToCompleted.cshtml
@{
    ViewBag.Title = "changeStatusToCompleted";
}

<h2>changeStatusToCompleted</h2>
<body>
    <h2>change Status To Completed</h2>
    <table style="width:100%">
        <tr>
            <th>Order Id</th>
            <th>TransportOwner</th>
            <th>Budget</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>completed</td>
            <td><a href=@Url.Action("","Admin")>confirm completed</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm completed</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>completed</td>
            <td><a href=@Url.Action("","Admin")>confirm completed</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>completed</td>
            <td><a href=@Url.Action("","Admin")>confirm completed</a></td>
        </tr>

    </table>
</body>

LoaderAppApi/Views/Admin/changeStatusToTransit.cshtml
@{
    ViewBag.Title = "changeStatusToTransit";
}

<body>
    <h2>change Status To Transit</h2>
    <table style="width:100%">
        <tr>
            <th>Order Id</th>
            <th>TransportOwner</th>
            <th>Budget</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm Transit</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm transit</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm transit</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm transit</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>transit</td>
            <td><a href=@Url.Action("","Admin")>confirm transit</a></td>
        </tr>

    </table>
</body>

LoaderAppApi/Views/Admin/updateOrderAsConfirmedToTransportOwner.cshtml
@{
    ViewBag.Title = "updateOrderAsConfirmedToTransportOwner";
}


<body>
    <h2>Send order confirmation to Transport Owner</h2>
    <table style="width:100%">
        <tr>
            <th>Pick Up</th>
            <th>Drop Off</th>
            <th>Comodity</th>
            <th>Weight</th>
            <th>PickUpDate</th>
            <th>Length</th>
            <th>Width</th>
            <th>Height</th>
            <th>ReceiverName</th>
            <th>ReceiverCompanyName</th>
            <th>AdditionalDetails</th>
            <th>Status</th>
            <th>Budget</th>
            <th>Send Confirmation</th>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>accepted</td>
            <td>ghi</td>
            <td><a href=@Url.Action("","Admin")>Send confirmation</a></td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>accepted</td>
            <td>ghi</td>
            <td><a href=@Url.Action("","Admin")>Send confirmation</a></td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>accepted</td>
            <td>ghi</td>
            <td><a href=@Url.Action("","Admin")>Send confirmation</a></td>
        </tr>
    </table>

</body>

LoaderAppApi/Views/Admin/viewAvailableOrders.cshtml
@{
    ViewBag.Title = "AvailableOrders";
}


<body>
    <h2>Available Orders</h2>
    <table style="width:100%">
        <tr>
            <th>Pick Up</th>
            <th>Drop Off</th>
            <th>Comodity</th>
            <th>Weight</th>
            <th>PickUpDate</th>
            <th>Length</th>
            <th>Width</th>
            <th>Height</th>
            <th>ReceiverName</th>
            <th>ReceiverCompanyName</th>
            <th>AdditionalDetails</th>
            <th>Status</th>
            <th>Budget</th>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
        <tr>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>abc</td>
            <td>def</td>
            <td>ghi</td>
            <td>ghi</td>
        </tr>
    </table>

</body>

LoaderAppApi/Views/Admin/viewAvailableQuotes.cshtml
@{
    ViewBag.Title = "viewAvailableQuotes";
}
<body>
<h2>Available Orders</h2>
<table style="width:100%">
    <tr>
        <th>Pick Up</th>
        <th>Drop Off</th>
        <th>Comodity</th>
        <th>Weight</th>
        <th>PickUpDate</th>
        <th>Length</th>
        <th>Width</th>
        <th>Height</th>
        <th>ReceiverName</th>
        <th>ReceiverCompanyName</th>
        <th>AdditionalDetails</th>
        <th>Status</th>
        <th>Budget</th>
        <th>See Quotes</th>
    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>
    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghi</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
    <tr>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>abc</td>
        <td>def</td>
        <td>ghi</td>
        <td>ghiiiiiiiiiiiii</td>
        <td><a href=@Url.Action("viewQuoteDetails","Admin")>proceed to view Quotes</a></td>

    </tr>
</table>

</body>

LoaderAppApi/Views/Admin/viewQuoteDetails.cshtml
@{
    ViewBag.Title = "QuoteDetails";
}

<body>
    <h2>Quote Details</h2>
    <table style="width:100%">
        <tr>
            <th>Order Id</th>
            <th>TransportOwner</th>
            <th>Budget</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>pending</td>
            <td><a href=@Url.Action("AcceptQuote","Admin")>Accept</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>pending</td>
            <td><a href=@Url.Action("AcceptQuote","Admin")>Accept</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>pending</td>
            <td><a href=@Url.Action("AcceptQuote","Admin")>Accept</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>pending</td>
            <td><a href=@Url.Action("AcceptQuote","Admin")>Accept</a></td>
        </tr>
        <tr>
            <td>11</td>
            <td>Joseph</td>
            <td>2400</td>
            <td>pending</td>
            <td><a href=@Url.Action("AcceptQuote","Admin")>Accept</a></td>
        </tr>

    </table>


</body>

LoaderAppApi/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

LoaderAppApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>